const text = [
  `Jelly sweet roll jelly beans biscuit pie macaroon chocolate donut. Carrot cake caramels pie sweet apple pie tiramisu carrot cake. Marzipan marshmallow croissant tootsie roll lollipop. Cupcake lemon drops bear claw gummies. Jelly bear claw gummi bears lollipop cotton candy gummi bears chocolate bar cake cookie. Cupcake muffin danish muffin cookie gummies. Jelly beans tiramisu pudding. Toffee soufflé chocolate cake pastry brownie. Oat cake halvah sweet roll cotton candy croissant lollipop. Macaroon tiramisu chocolate bar candy candy carrot cake jelly sweet. Gummies croissant macaroon dessert. Chocolate cake dragée pie.`,
  `Next level tbh everyday carry, blog copper mug forage kitsch roof party pickled hammock kale chips tofu. Etsy shoreditch 8-bit microdosing, XOXO viral butcher banh mi humblebrag listicle woke bicycle rights brunch before they sold out ramps. Twee shabby chic taiyaki flannel, enamel pin venmo vape four loko. Hexagon kale chips typewriter kitsch 8-bit organic plaid small batch keffiyeh ethical banh mi narwhal echo park cronut.`,
  `Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.`,
  `Cat gets stuck in tree firefighters try to get cat down firefighters get stuck in tree cat eats firefighters' slippers kitty power ignore the squirrels, you'll never catch them anyway for what a cat-ass-trophy! or purr as loud as possible, be the most annoying cat that you can, and, knock everything off the table. Pretend you want to go out but then don't bite off human's toes, yet disappear for four days and return home with an expensive injury; bite the vet so catch eat throw up catch eat throw up bad birds. `,
  `This opera's as lousy as it is brilliant! Your lyrics lack subtlety. You can't just have your characters announce how they feel. That makes me feel angry! Anyhoo, your net-suits will allow you to experience Fry's worm infested bowels as if you were actually wriggling through them.
I just told you! You've killed me! Fry! Quit doing the right thing, you jerk! Michelle, I don't regret this, but I both rue and lament it. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.`,
  `Airedale hard cheese mozzarella. Pecorino melted cheese port-salut emmental babybel cheese and wine melted cheese manchego. Everyone loves blue castello everyone loves fromage cheese slices airedale cheddar cream cheese. Bavarian bergkase who moved my cheese halloumi port-salut gouda jarlsberg ricotta rubber cheese. Stinking bishop smelly cheese brie.`,
  `Salvia glossier subway tile, leggings mustache YOLO semiotics chia. Pitchfork tbh af blog church-key meggings vaporware PBR&B master cleanse post-ironic man bun pabst mustache letterpress synth. Snackwave raw denim godard, 3 wolf moon shaman offal kitsch unicorn live-edge selvage schlitz fashion axe vaporware drinking vinegar prism. Shabby chic tacos artisan, chambray chicharrones cardigan leggings typewriter af pop-up williamsburg meditation PBR&B viral. You probably haven't heard of them DIY jean shorts subway tile fashion axe bushwick kitsch tumeric cloud bread vaporware freegan franzen pork belly chicharrones banh mi.`,
  `Man braid celiac synth freegan readymade, pitchfork fam salvia waistcoat lomo bitters gentrify four loko. Pitchfork semiotics post-ironic vegan. Tofu meditation microdosing hashtag semiotics venmo. Flexitarian vape tilde taiyaki. Prism poutine farm-to-table, messenger bag vegan taxidermy tattooed sartorial squid jean shorts fixie selvage trust fund vape.`,
  `Rutters Plate Fleet boom chandler Brethren of the Coast handsomely lookout marooned brigantine knave. Buccaneer gangway jack rum loot spyglass line Jack Tar fore gaff. Gaff topmast scuttle ballast swab draught measured fer yer chains dance the hempen jig Chain Shot yardarm.`,
  `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor id eu nisl nunc mi ipsum faucibus vitae. Condimentum mattis pellentesque id nibh tortor id aliquet lectus. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus. Purus sit amet luctus venenatis. Ac tincidunt vitae semper quis lectus nulla at. Tincidunt eget nullam non nisi est sit amet facilisis. Eget velit aliquet sagittis id. Morbi blandit cursus risus at ultrices mi. Eu turpis egestas pretium aenean. Neque viverra justo nec ultrices dui sapien eget mi proin. Consectetur adipiscing elit duis tristique sollicitudin nibh sit. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet. Iaculis eu non diam phasellus vestibulum lorem sed risus ultricies. Ut enim blandit volutpat maecenas volutpat blandit. Bibendum neque egestas congue quisque egestas diam in. Velit scelerisque in dictum non. Fermentum et sollicitudin ac orci phasellus.`,
  `Congue mauris rhoncus aenean vel elit scelerisque mauris. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Pharetra pharetra massa massa ultricies. Sollicitudin nibh sit amet commodo. Tellus mauris a diam maecenas sed enim. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. At imperdiet dui accumsan sit amet nulla facilisi. Orci nulla pellentesque dignissim enim sit amet venenatis. Nullam vehicula ipsum a arcu cursus vitae congue mauris rhoncus. Est ultricies integer quis auctor elit sed. Eget felis eget nunc lobortis. Id volutpat lacus laoreet non curabitur gravida arcu ac tortor. Elit duis tristique sollicitudin nibh. Neque aliquam vestibulum morbi blandit cursus. Diam sollicitudin tempor id eu nisl nunc mi. Etiam sit amet nisl purus in mollis nunc. Diam in arcu cursus euismod quis.`,
  `Fermentum posuere urna nec tincidunt praesent semper feugiat nibh sed. Venenatis cras sed felis eget velit aliquet sagittis. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Dapibus ultrices in iaculis nunc sed augue lacus viverra. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sed viverra tellus in hac habitasse platea dictumst vestibulum. Faucibus scelerisque eleifend donec pretium vulputate. Faucibus scelerisque eleifend donec pretium vulputate sapien. Eget nulla facilisi etiam dignissim diam quis enim. Id aliquet risus feugiat in ante. Dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Eget egestas purus viverra accumsan in nisl nisi scelerisque eu. Mi bibendum neque egestas congue. Eu sem integer vitae justo eget magna fermentum. Nibh tortor id aliquet lectus proin nibh nisl. Id neque aliquam vestibulum morbi blandit. Adipiscing elit pellentesque habitant morbi tristique senectus et.`,
  `Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl. Sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Ornare arcu odio ut sem nulla pharetra. Sodales ut etiam sit amet nisl purus in mollis. Posuere lorem ipsum dolor sit. Vel quam elementum pulvinar etiam non quam. Odio morbi quis commodo odio aenean sed adipiscing diam. Elementum nisi quis eleifend quam adipiscing vitae proin sagittis. Et netus et malesuada fames ac turpis egestas integer eget. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Vel turpis nunc eget lorem dolor sed viverra. Tempor orci dapibus ultrices in iaculis nunc sed. Tellus cras adipiscing enim eu turpis egestas pretium aenean. Dolor sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Vel eros donec ac odio tempor orci. Odio eu feugiat pretium nibh ipsum consequat nisl vel pretium. Gravida dictum fusce ut placerat.`,
  `Pharetra et ultrices neque ornare. Dolor magna eget est lorem ipsum. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Natoque penatibus et magnis dis parturient. Molestie at elementum eu facilisis sed odio. Euismod lacinia at quis risus sed vulputate odio ut. Interdum varius sit amet mattis. Nisi lacus sed viverra tellus in hac habitasse platea. Mi sit amet mauris commodo quis imperdiet. Libero volutpat sed cras ornare arcu dui vivamus. Dolor sit amet consectetur adipiscing elit duis tristique sollicitudin. A erat nam at lectus urna duis convallis convallis tellus. Risus in hendrerit gravida rutrum quisque non tellus orci.`,
];
export default text;
